spring:
  application:
    name: hrjob-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # ... other datasource properties ...
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrjob?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: your_username
    password: your_password

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.zg.hrjob_server.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-spring.xml

api:
  url:
    floor-layout: http://api.example.com/floor-layout
    work-orders: http://api.example.com/work-orders
    precise-work-orders: http://api.example.com/precise-work-orders